//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenSspContext : DbContext
    {
        public OpenSspContext()
            : base("name=OpenSspContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Housing> Housing { get; set; }
        public virtual DbSet<Residence> Residence { get; set; }
        public virtual DbSet<Room> Room { get; set; }
    }
}
