//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residence
    {
        public int Id { get; set; }
        public System.Guid RoomGuid { get; set; }
        public System.Guid ClientGuid { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Room Room { get; set; }
    }
}
