//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Residence = new HashSet<Residence>();
        }
    
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> CostPerDay { get; set; }
        public Nullable<double> CostService { get; set; }
        public Nullable<System.Guid> HousingGuid { get; set; }
    
        public virtual Housing Housing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Residence> Residence { get; set; }
    }
}
